name: AntiPayloadHax
version: 1.0.0
main: com.relatev.minecraft.antipayloadhax.AntiPayloadHax
softdepend: [ProtocolLib]
commands:
  AntiPayloadHax:
    description: AntiPayloadHax
    usage: /AntiPayloadHax
    aliases: [aph]